# Generated by Django 3.1.7 on 2021-03-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=50)),
                ('race_description', models.TextField()),
                ('race_str_bonus', models.IntegerField()),
                ('race_dex_bonus', models.IntegerField()),
                ('race_con_bonus', models.IntegerField()),
                ('race_int_bonus', models.IntegerField()),
                ('race_wis_bonus', models.IntegerField()),
                ('race_cha_bonus', models.IntegerField()),
                ('race_spd', models.IntegerField()),
                ('race_darkvision', models.BooleanField()),
                ('race_has_subrace', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_race_name', models.CharField(max_length=50)),
                ('sub_race_description', models.TextField()),
                ('sub_race_str_bonus', models.IntegerField()),
                ('sub_race_dex_bonus', models.IntegerField()),
                ('sub_race_con_bonus', models.IntegerField()),
                ('sub_race_int_bonus', models.IntegerField()),
                ('sub_race_wis_bonus', models.IntegerField()),
                ('sub_race_cha_bonus', models.IntegerField()),
                ('sub_race_spd', models.IntegerField()),
                ('sub_race_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.race')),
            ],
        ),
    ]
