# Generated by Django 3.1.7 on 2021-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.TextField()),
                ('class_hit_die', models.IntegerField()),
                ('class_primary_ability', models.CharField(max_length=50)),
                ('class_save_throw1', models.CharField(max_length=4)),
                ('class_save_throw2', models.CharField(max_length=4)),
                ('class_armor_and_weapons', models.TextField()),
            ],
        ),
    ]
