# Generated by Django 3.1.7 on 2021-03-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_has_special',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
