# Generated by Django 3.1.7 on 2021-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_race_race_has_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_img',
            field=models.TextField(default='https://static.wikia.nocookie.net/forgottenrealms/images/b/b6/Dwarf-5e.png/revision/latest/scale-to-width-down/420?cb=20180814005205'),
            preserve_default=False,
        ),
    ]
