# Generated by Django 3.1.7 on 2021-03-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_race_race_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_armor_and_weapons',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_primary_ability',
        ),
        migrations.AddField(
            model_name='class',
            name='class_armor',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_weapons',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_save_throw1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_save_throw2',
            field=models.CharField(max_length=15),
        ),
    ]
