# Generated by Django 3.1.7 on 2021-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20210318_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_image',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
