# Generated by Django 3.1.7 on 2021-03-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20210319_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_first_hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_later_hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_later_hp_avg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
