# Generated by Django 3.1.7 on 2021-03-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_skills_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
