# Generated by Django 3.1.7 on 2021-03-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20210319_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.class')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_skill', to='character.skill')),
            ],
        ),
    ]
