# Generated by Django 3.1.7 on 2021-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_classskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_num_skills',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
