# Generated by Django 3.1.7 on 2021-03-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_auto_20210320_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classskill',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AddField(
            model_name='skill',
            name='class_name',
            field=models.ManyToManyField(blank=True, related_name='skill_list', to='character.Class'),
        ),
        migrations.DeleteModel(
            name='ClassSkill',
        ),
    ]
