# Generated by Django 3.1.7 on 2021-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_auto_20210320_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='class_name',
        ),
        migrations.AddField(
            model_name='class',
            name='class_skills',
            field=models.ManyToManyField(related_name='skill_list', to='character.Skill'),
        ),
    ]
