# Generated by Django 3.1.7 on 2021-03-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
