# Generated by Django 3.1.7 on 2021-03-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_auto_20210320_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_tools',
            field=models.ManyToManyField(related_name='tool_list', to='character.Tool'),
        ),
    ]
