# Generated by Django 3.1.7 on 2021-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0018_class_class_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_url',
            field=models.TextField(default='https://www.dandwiki.com/wiki/5e_SRD:Athletics_Skill'),
            preserve_default=False,
        ),
    ]
