# Generated by Django 3.1.7 on 2021-04-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0021_bond_ideal_personalitytrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_lanagues', models.IntegerField()),
                ('skills', models.ManyToManyField(related_name='background_skill_list', to='character.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='bond',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='background_bonds', to='character.background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideal',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='background_ideals', to='character.background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalitytrait',
            name='background',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='background_traits', to='character.background'),
            preserve_default=False,
        ),
    ]
