# Generated by Django 3.1.7 on 2021-04-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_auto_20210401_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='num_lanagues',
            new_name='num_languages',
        ),
    ]
