# Generated by Django 3.1.7 on 2021-04-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0024_flaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='background',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='background_flaws', to='character.background'),
            preserve_default=False,
        ),
    ]
