# Generated by Django 3.1.7 on 2021-04-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0026_background_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
