# Generated by Django 3.1.7 on 2021-04-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0027_weaponcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dmg', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_category', to='character.weaponcategory')),
                ('properties', models.ManyToManyField(related_name='weapon_properties', to='character.WeaponProperty')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weap_type', to='character.weapontype')),
            ],
        ),
    ]
